### ISSUE TITLE
Data Question

### ISSUE THREAD

**Issue by justinelliotmeyers** [MIMAXUZ/uzbekistan-regions-data#12]
Hello!
I'd like to help update this dataset with names and possibly latitude/ longitude coordinates. Is this project still alive?
Thanks!

**Comment by MIMAXUZ** [comment]
Hi, thanks for interesting to our project.
Of course you can help.  We'll be happy with that.  If you have any changes, we can review and confirm if you leave a request.
Regards.

**Comment by justinelliotmeyers** [comment]
I've been trying to communicate with the people at https://geonames.kadastr.uz/ but they are not responding to emails. Same with the people at https://dshk.uz/uz/

Have you communicated with either of these bureaus/ agencies? I believe they have information that can assist with this

**Comment by MIMAXUZ** [comment]
No.  We did not work closely with these organizations.  We received and collected this information from the official website https://my.gov.uz.  We used the websites of each region and the decisions on https://lex.uz.

**Comment by justinelliotmeyers** [comment]
kadastr.uz has a Saytdagi barcha materiallardan quyidagi lisenziya bo‘yicha foydalanish mumkin: [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)

https://dshk.uz/uz/ has unknown terms of use/ copyright. Can you possible email this agency or call them to clarify - Then we can start to update actual location data (geojson/ shapefile/ latitutude/ longitude) 
Telefon: +(998) 71 273-04-82
Email address: info@uzgashkliti.uz
Address: O'zbekiston, Toshkent, Qatortol ko'chasi 38

Again, I've been emailing both of these agencies for weeks in uzbek, russian, and english and they do not respond to emails. So I am stuck! But want to collaborate to help here as well!

**Comment by justinelliotmeyers** [comment]
I posted the main two admins here: https://revolutionarygis.wordpress.com/2023/04/19/%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d0%b5-%d0%be%d0%b1-%d0%b0%d0%b4%d0%bc%d0%b8%d0%bd%d0%b8%d1%81%d1%82%d1%80%d0%b0%d1%82%d0%b8%d0%b2%d0%bd%d0%be-%d1%82%d0%b5%d1%80%d1%80%d0%b8%d1%82%d0%be%d1%80%d0%b8/

I need to begin to update villages/ towns/ settlements now.

**Comment by MIMAXUZ** [comment]
Ok. We'll try to contact eith them. But i think this is not help. Becaouse thry doesn't support via email.

**Comment by justinelliotmeyers** [comment]
You are local (in Uzbekistan). Would be much easier for you to call or e-mail in language instead of me trying with broken translations! Hopefully this data will help and we can create a nice dataset!

**Comment by justinelliotmeyers** [comment]
I have some data for Uzbekistan - but having official government agencies help clarify and confirm both names and latitude/ longitude would fill in gaps and cross verify data.

If you could ask them for names/ latitude/ longitude that would be great.

If they cannot share I understand.

If you could get clear terms of use/ copyright from https://dshk.uz/uz/ I might be able to use what they have to create. But I cannot unless I understand if they allow it or now through their copyright.

**Comment by justinelliotmeyers** [comment]
https://stat.uz/ru/2020-05-11-05-05-43/statisticheskie-klassifikatory
https://stat.uz/images/soato-20_04_2022.xlsx

**Comment by justinelliotmeyers** [comment]
Hey! I just wanted to follow-up. I know communicating with their agencies is a challenge, but wanted to see if you had any luck yet?

Appreciate it,
Justin
