### ISSUE TITLE
Mana tumanlar bo'yicha TO'LIQ geoJSON ma'lumotlar

### ISSUE THREAD

**Issue by sherali-1** [MIMAXUZ/uzbekistan-regions-data#13]
OpenStreet Map dan olingan

1) https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-uzbekistan/resource/4b514e0a-1fb1-45e8-97a8-15a46019ca6e

2) other lists are there: https://data.humdata.org/dataset/geoboundaries-admin-boundaries-for-uzbekistan

bitta formatga solib tashlab quysa yaxshi bo'lardi menimcha

**Comment by justinelliotmeyers** [comment]
https://revolutionarygis.wordpress.com/2023/04/19/%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d0%b5-%d0%be%d0%b1-%d0%b0%d0%b4%d0%bc%d0%b8%d0%bd%d0%b8%d1%81%d1%82%d1%80%d0%b0%d1%82%d0%b8%d0%b2%d0%bd%d0%be-%d1%82%d0%b5%d1%80%d1%80%d0%b8%d1%82%d0%be%d1%80%d0%b8/

**Comment by MIMAXUZ** [comment]
Ma'lumotlar tez orada qayta yangilanadi. Yuqorida keltirilgan mabaalar doimiy yangilanmaganligi sababli ulardan foydalanilmagan. Tez orada davlat orgenlariga mos SOATO lar bilan birgalikda yangi versiyani taqdim etamiz.

**Comment by justinelliotmeyers** [comment]
Do you know when? Or have you been in communication with any agencies?

**Comment by MIMAXUZ** [comment]
> Do you know when? Or have you been in communication with any agencies?

Currently being developed in collaboration with the Single Portal (my.gov.uz). The information has been corrected. Time is a problem. We will upload this data to github as soon as we have time.
Regards.
