### ISSUE TITLE
Correctly rendering cyrillic names

### ISSUE THREAD

**Issue by gofurnazarov** [MIMAXUZ/uzbekistan-regions-data#3]
How can I correctly render rendering Cyrillic names?

![Capture](https://user-images.githubusercontent.com/26648861/152727875-064955ff-646d-4b72-a785-1b31614385f9.png)

**Comment by MIMAXUZ** [comment]
Hi. Thanks for interesting to our project.
You don’t have to render it.  If you open it using a normal URL, the format will look wrong.  If you used JSON in the program, everything will be in place.
